# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cheerp's Wiki
description: >- # this means to ignore newlines until "baseurl:"
  Main documentation and tutorials for Cheerp | the C++ compiler for the Web.
  Edit directly any markdown file in the cheerp-meta repository to have it automatically updated.
baseurl: "/cheerp-meta" # the subpath of your site, e.g. /blog
logo: "/assets/cheerp_logo.png"   # Change to relevant file
tagline:
  line1: "The C++ compiler for the Web"
  line2: "Documentation & Tutorials"

# Build settings
markdown: kramdown
remote_theme: carlopi/leaningtech-docs

plugins:
 - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: "https://opengraph.githubassets.com/bc9dec9762126442f3c47aae6d7a8b5ef888607053adc47f358121bd2a878cb0/carlopi/cheerp-meta"

repository: https://github.com/carlopi/cheerp-meta
website: https://leaningtech.com/cheerp/
issues: https://github.com/leaningtech/cheerp-meta/issues
chat: https://gitter.im/leaningtech/cheerp
blog: https://medium.com/leaningtech
has_about: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
